import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        let news = [
            { id: 0, title: 'Hacker Wars Released', date: '8.22.2011', localurl: 'hacker_wars.html', image: 'images/appicons/hackerwars_icon.png', text: 'Just when you thought Mahjong solitaire had been covered, along comes a new, fast paced Mahjong solitaire game where matching tiles are used as methods of attack in a virtual war. A truly unique and action packed twist on the classic Mahjong solitaire game.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.hackers.free' },
            { id: 1, title: 'Halloween Screamscape Released', date: '9.27.2011', localurl: 'screamscape.html', image: 'images/appicons/screamscape_icon.png', text: 'Halloween Screamscape is a spooky stroll through a moonlit landscape. Scenery includes a haunted forest, a grave yard, a haunted pumpkin patch and occasional visits from witches, ghosts, zombies, and the grim reaper himself.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.halloween' },
            { id: 2, title: '8 Bit Mahjong Released', date: '11.27.2011', localurl: 'eightbit_mahjong.html', image: 'images/appicons/eightbit_icon.png', text: '8 Bit Mahjong is the classic Mahjong solitaire game re-imagined for an 8 bit world. The goal is to remove all of the tiles from the board. You may remove only paired free tiles. The tile is free when there are no tiles either to the left or to the right of it.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.eightbit.free' },
            { id: 3, title: 'Christmas Mahjong Released', date: '12.01.2011', localurl: 'xmas_mahjong.html', image: 'images/appicons/xmas_icon.png', text: 'Christmas Mahjong is the classic Mahjong solitaire game with a cute Christmas theme. The goal is to remove all of the tiles from the board. You may remove only paired free tiles. The tile is free when there are no tiles either to the left or to the right of it.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.xmas.free' },
            { id: 4, title: 'Christmas Dreamscape Released', date: '12.04.2011', localurl: 'dreamscape.html', image: 'images/appicons/christmas_icon.png', text: 'Christmas Dreamscape is a cheerful stroll through a snowy landscape. Scenery includes mountains, Christmas trees, snowmen, and a colorful Christmas village.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.christmas' },
            { id: 5, title: 'Alien Dance Party Released', date: '01.04.2012', localurl: 'dance_party.html', image: 'images/appicons/alien_icon.png', text: 'Keep the party rocking with Alien Dance Party! Challenge your memory with this Simon-like game by matching the correct pattern to keep your aliens busting their best moves. The longer the party goes on, the greater the challenge! Can you keep your alien dancing all night?', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.dance.free' },
            { id: 6, title: 'Halloween Screamscape Free Released', date: '8.26.2012', localurl: 'screamscape.html', image: 'images/appicons/screamscape_icon.png', text: 'The free version of Halloween Screamscape is a spooky stroll through a moonlit landscape. Scenery includes a haunted forest, houses, a grave yard, a haunted pumpkin patch. Animated witches, ghosts, zombies, bats and the Grim Reaper from the paid version can be added with a simple in-app purchase.', remoteurl: 'http://play.google.com/store/apps/details?id=com.random.halloween.free' },
            { id: 7, title: 'Halloween Dance Party Released', date: '09.14.2012', localurl: 'halloween_dance.html', image: 'images/appicons/halloween_icon.png', text: 'Keep the party rocking with Halloween Dance Party! Challenge your memory with this Simon-like game by matching the correct pattern to keep your creeps busting their best moves. The longer the party goes on, the greater the challenge! Can you keep yourcreep dancing all night?', remoteurl: 'https://play.google.com/store/apps/details?id=com.random.halloween.dance.free' },
        ];
        return { news };
    }
}

 
